# Generated by Django 3.2.6 on 2021-08-16 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.FloatField(help_text='Capacity of the container in Liters.')),
                ('cost', models.FloatField(help_text='Cost of the keg, in your desired unit.')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('capacity', models.FloatField(help_text='Capacity of the container in Liters.')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('style', models.CharField(blank=True, default='', max_length=200)),
                ('producer', models.CharField(blank=True, default='', max_length=200)),
                ('abv', models.FloatField(default=0, help_text='Alcohol By Volume.')),
            ],
        ),
        migrations.CreateModel(
            name='Tap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('onTap', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drink_consumption.container')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='**Auto-created Tag**', max_length=200)),
                ('uid', models.CharField(max_length=200, unique=True)),
                ('linked_container', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='drink_consumption.personalcontainer')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Refill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('container', models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='drink_consumption.personalcontainer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='drink_consumption.container')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drink_consumption.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='**Auto-created Reader**', max_length=200)),
                ('physical_id', models.CharField(max_length=200, unique=True)),
                ('forTap', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drink_consumption.tap')),
            ],
        ),
        migrations.AddField(
            model_name='container',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='drink_consumption.product'),
        ),
    ]
