# Generated by Django 3.2.6 on 2021-08-20 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drink_consumption', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='initial_content',
            field=models.FloatField(blank=True, help_text='Capacity of the container in Liters.', null=True),
        ),
    ]
